apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-cubejs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-cubejs
  template:
    metadata:
      labels:
        app: poc-cubejs
    spec:
      containers:
        - name: poc-cubejs
          image: nginx:1.26-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
