apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: outbox
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: outbox-a
            chartVersion: 22.6.1
          - name: outbox-b
            chartVersion: 22.6.0
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      sources:
        - repoURL: https://charts.bitnami.com/bitnami
          chart: nginx
          targetRevision: '{{.chartVersion}}'
          helm:
            releaseName: '{{.name}}'
            valueFiles:
              - $values/services/{{.name}}/values.yaml
        - repoURL: https://github.com/trojocerqlar/argocd-test.git
          targetRevision: main
          ref: values