apiVersion: v1
kind: Secret
metadata:
  name: backend-service-credentials
  labels:
    app.kubernetes.io/name: backend-service-credentials
    app.kubernetes.io/part-of: progressive-sync-poc
type: Opaque
stringData:
  POSTGRES_HOST: postgres-db
  POSTGRES_DB: orders
  POSTGRES_USER: demo
  POSTGRES_PASSWORD: demo
  MONGO_URI: mongodb://demo:demo@mongo-db:27017/catalog?authSource=admin
