env: dev
slackKey: dev
prune: "true"
selfHeal: "true"      # set "false" here to give production a guardrail
services:
  - service: service-a
    chartVersion: "25.0.5"
  - service: service-b
    chartVersion: "25.0.5"
    url: "https://example.com"
  - service: service-a-outbox
    chartVersion: "25.0.5"
