apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/trojocerqlar/argocd-test.git
              revision: main
              files:
                - path: appssets/envs/*.yaml
          - list:
              elementsYaml: "{{ .services | toJson }}"
  template:
    metadata:
      name: '{{ .env }}-{{ .service }}'
      labels:
        env: '{{ .env }}'
        service: '{{ .service }}'
    spec:
      project: services
      sources:
        - repoURL:  https://charts.bitnami.com/bitnami
          chart: nginx
          targetRevision: '{{ .chartVersion }}'
          helm:
            releaseName: '{{ .path.basename }}'
            valueFiles:
              - $values/apps/{{ .path.basename }}/values.{{ .env }}.yaml
              - $values/apps/{{ .path.basename }}/secrets.{{ .env }}.yaml
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/trojocerqlar/argocd-test.git
          targetRevision: main
          ref: values
      destination:
        name: '{{ .cluster }}'
        namespace: cerqlar-{{ .env }}
      syncPolicy:
        automated:
          prune: "{{ .prune }}"
          selfHeal: "{{ .selfHeal }}"
  templatePatch: |
    metadata:
      annotations:
        {{- if hasKey . "url" }}
        link.argocd.argoproj.io/external-link: "{{ .url }}"
        {{- end }}