apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/trojocerqlar/argocd-test.git
              revision: main
              files:
                - path: apps/*/config.yaml
          - list:
              elements:
                - env: dev
                  cluster: in-cluster
                - env: prd
                  cluster: in-cluster
  template:
    metadata:
      name: '{{ .path.basename }}-{{ .env }}'
      labels:
        env: '{{ .env }}'
        service: '{{ .path.basename }}'
    spec:
      project: services
      sources:
        - repoURL:  https://charts.bitnami.com/bitnami
          chart: nginx
          targetRevision: '{{ .chartVersion }}'
          helm:
            releaseName: '{{ .path.basename }}'
            valueFiles:
              - $values/apps/{{ .path.basename }}/values.yaml
              - $values/apps/{{ .path.basename }}/values.{{ .env }}.yaml
              - $values/apps/{{ .path.basename }}/secrets.{{ .env }}.yaml
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/trojocerqlar/argocd-test.git
          targetRevision: main
          ref: values
      destination:
        name: '{{ .cluster }}'
        namespace: cerqlar-{{ .env }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          {{- if .serverSideApply }}
          - ServerSideApply=true
          {{- end }}