apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - git:
        repoURL: https://github.com/trojocerqlar/argocd-test.git
        revision: main
        files:
          - path: catalog/apps/*.yaml

  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: stage
              operator: In
              values:
                - infrastructure
        - matchExpressions:
            - key: stage
              operator: In
              values:
                - services
        - matchExpressions:
            - key: stage
              operator: In
              values:
                - outbox

  template:
    metadata:
      name: '{{.name}}'
      labels:
        stage: '{{.stage}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  templatePatch: |
    spec:
      {{- if eq .type "directory" }}
      source:
        repoURL: https://github.com/trojocerqlar/argocd-test.git
        targetRevision: main
        path: {{ .path }}
      {{- else if eq .type "helm" }}
      sources:
        - repoURL: https://charts.bitnami.com/bitnami
          chart: nginx
          targetRevision: '{{ .chartVersion }}'
          helm:
            releaseName: '{{ .name }}'
            valueFiles:
              - '$values/{{ .valuesFile }}'
        - repoURL: https://github.com/trojocerqlar/argocd-test.git
          targetRevision: main
          ref: values
      {{- end }}
